---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: Copy Metricbeat config file
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Run modules enable docker
    command: metricbeat modules enable docker

  - name: metricbeat setup
    command: metricbeat setup

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat.service
      enabled: yes
